# Generated by Django 4.1 on 2022-08-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_dex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='owner',
        ),
    ]
