# Generated by Django 4.1 on 2022-08-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_dex', '0005_alter_record_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
