# Generated by Django 4.1 on 2022-08-27 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_dex', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_dex.category'),
        ),
        migrations.AlterField(
            model_name='record',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
