# Generated by Django 4.1 on 2022-08-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_dex', '0008_category_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(default='New Upload', max_length=50),
        ),
    ]
