# Generated by Django 4.1 on 2022-08-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_dex', '0009_alter_record_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
